name: Build and Deploy

on:
  push:
    branches: [ "main" ] # Chạy mỗi khi bạn push code lên nhánh main

permissions:
  contents: write # Cần quyền này để Action có thể đẩy bản build lên nhánh gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - run: npm install
      - run: npm run build
        env:
          VITE_EMAILJS_SERVICE_ID: ${{ secrets.VITE_EMAILJS_SERVICE_ID }}
          VITE_EMAILJS_TEMPLATE_ID: ${{ secrets.VITE_EMAILJS_TEMPLATE_ID }}
          VITE_EMAILJS_PUBLIC_KEY: ${{ secrets.VITE_EMAILJS_PUBLIC_KEY }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Thư mục chứa kết quả build (Vite thường là dist, React cũ là build)
          branch: gh-pages # Nhánh mà GitHub Pages sẽ dùng để hiển thị website
